name = "servicelnina-web"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[build.upload]
format = "service-worker"

[env.production]
name = "servicelnina-web-prod"
route = "servicelnina.com/*"
zone_id = ""
